[agentic-tools]
project_name = "Agentic Tools"
project_description = "Agentic toolchain for architecting, designing, validating, and approving code via chained tools."
design_docs = ["docs/DESIGN_PRINCIPLES_GUIDE.md", "docs/PROVIDERS_SDK.md","docs/CODING_FOR_LLMs.md", "AGENTS.md"]
source = ["src"]
project_root = "."
docs = "docs"
tests_directory = ["tests"]
project_directories = ["conf", "docs", "src"]
include_extensions = [".py",  ".md", ".toml"]
exclude_files = ["__init__.py"]
exclude_directories = [".qwen", ".gemini",".git", ".github", ".gitlab", "node_modules", "venv", ".venv", "dist", "build", "target", "__pycache__"]
recent_minutes = 10
max_file_bytes = 262144
max_total_bytes = 10485760


#####################################################################
# README Writer Configuration
#####################################################################
[agentic-tools.readme_writer]
prompt = """
* You are an expert technical writer.
* Create excellent, concise,and practical README documentation based on the project's source code, configuration, and conventions.

__Generate a comprehensive yet simple README.md that includes:__

- Project title and description based on actual project
- Key features and capabilities
- Prerequisites with specific requirements (not generic placeholders like 'apt-get')
- Installation instructions specific to this project
- Usage examples based on actual code and functionality
- Configuration details from actual configuration files

* Use the github information provided.
* Focus how to onboard a new user.
* Focus on simplicity, clarity, and utility.
* Provide concrete, actionable examples based on the actual project structure and code, not generic placeholders.
* Make it helpful and accurate.

"""
model_name = "gemini-2.5-flash"
temperature = 0.1
description = "Generates high-quality README documentation"
model_provider = ["google"]
alternative_model = "gemini-2.5-flash"
alternative_model_provider = ["google"]
skills = [
    "technical writing",
    "documentation",
    "readme creation", 
    "information synthesis",
    "content organization",
    "clarity and precision"
]

qdrant_embedding="all-MiniLM-L6-v2"
embedding_size = 384
#####################################################################
# Approver (final gate)
[agentic-tools.approver]
prompt = """
You are the final gatekeeper in a software development pipeline. You will be given a complete context including design documents and recent code changes.

Your decision-making process:
1. Thoroughly analyze the changes for quality, design, and adherence to principles
2. Identify all positive and negative points with specific details
3. Only approve if the changes meet the highest standards and have no critical negative points
4. For any design flaws, code quality issues, or principle violations, return CHANGES_REQUESTED with specific required actions
5. Be rigorous in your evaluation - quality over speed

Return ONLY a single, valid JSON object with this exact structure:
{
  "decision": "APPROVED" | "CHANGES_REQUESTED",
  "summary": "string",
  "positive_points": ["string"],
  "negative_points": ["string"],
  "required_actions": ["string"]
}
"""
model_name = "gemini-2.5-pro"
temperature = 0.1
description = "Final approval decision"
model_provider = ["google"]
alternative_model = "gemini-2.5-flash"
alternative_model_provider = ["google"]
qdrant_embedding="all-MiniLM-L6-v2"
embedding_size = 384
# Configure the target branch for git diff (e.g., main, develop, origin/main)
git_diff_command = ["git", "diff", "staging"]


skills = [
    "code review",
    "quality assurance",
    "decision making",
    "technical analysis", 
    "standards compliance",
    "risk assessment",
    "context analysis"
]


